// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateVMOpts struct {
	StemcellID           string   `protobuf:"bytes,1,opt,name=stemcellID,proto3" json:"stemcellID,omitempty"`
	AgentSettings        []byte   `protobuf:"bytes,2,opt,name=agentSettings,proto3" json:"agentSettings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVMOpts) Reset()         { *m = CreateVMOpts{} }
func (m *CreateVMOpts) String() string { return proto.CompactTextString(m) }
func (*CreateVMOpts) ProtoMessage()    {}
func (*CreateVMOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{0}
}
func (m *CreateVMOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMOpts.Unmarshal(m, b)
}
func (m *CreateVMOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMOpts.Marshal(b, m, deterministic)
}
func (dst *CreateVMOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMOpts.Merge(dst, src)
}
func (m *CreateVMOpts) XXX_Size() int {
	return xxx_messageInfo_CreateVMOpts.Size(m)
}
func (m *CreateVMOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMOpts.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMOpts proto.InternalMessageInfo

func (m *CreateVMOpts) GetStemcellID() string {
	if m != nil {
		return m.StemcellID
	}
	return ""
}

func (m *CreateVMOpts) GetAgentSettings() []byte {
	if m != nil {
		return m.AgentSettings
	}
	return nil
}

type AttachDisksOpts struct {
	VmID                 string   `protobuf:"bytes,1,opt,name=vmID,proto3" json:"vmID,omitempty"`
	DiskID               string   `protobuf:"bytes,2,opt,name=diskID,proto3" json:"diskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachDisksOpts) Reset()         { *m = AttachDisksOpts{} }
func (m *AttachDisksOpts) String() string { return proto.CompactTextString(m) }
func (*AttachDisksOpts) ProtoMessage()    {}
func (*AttachDisksOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{1}
}
func (m *AttachDisksOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachDisksOpts.Unmarshal(m, b)
}
func (m *AttachDisksOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachDisksOpts.Marshal(b, m, deterministic)
}
func (dst *AttachDisksOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachDisksOpts.Merge(dst, src)
}
func (m *AttachDisksOpts) XXX_Size() int {
	return xxx_messageInfo_AttachDisksOpts.Size(m)
}
func (m *AttachDisksOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachDisksOpts.DiscardUnknown(m)
}

var xxx_messageInfo_AttachDisksOpts proto.InternalMessageInfo

func (m *AttachDisksOpts) GetVmID() string {
	if m != nil {
		return m.VmID
	}
	return ""
}

func (m *AttachDisksOpts) GetDiskID() string {
	if m != nil {
		return m.DiskID
	}
	return ""
}

type DataParcel struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataParcel) Reset()         { *m = DataParcel{} }
func (m *DataParcel) String() string { return proto.CompactTextString(m) }
func (*DataParcel) ProtoMessage()    {}
func (*DataParcel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{2}
}
func (m *DataParcel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataParcel.Unmarshal(m, b)
}
func (m *DataParcel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataParcel.Marshal(b, m, deterministic)
}
func (dst *DataParcel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataParcel.Merge(dst, src)
}
func (m *DataParcel) XXX_Size() int {
	return xxx_messageInfo_DataParcel.Size(m)
}
func (m *DataParcel) XXX_DiscardUnknown() {
	xxx_messageInfo_DataParcel.DiscardUnknown(m)
}

var xxx_messageInfo_DataParcel proto.InternalMessageInfo

func (m *DataParcel) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TruthParcel struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruthParcel) Reset()         { *m = TruthParcel{} }
func (m *TruthParcel) String() string { return proto.CompactTextString(m) }
func (*TruthParcel) ProtoMessage()    {}
func (*TruthParcel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{3}
}
func (m *TruthParcel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruthParcel.Unmarshal(m, b)
}
func (m *TruthParcel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruthParcel.Marshal(b, m, deterministic)
}
func (dst *TruthParcel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruthParcel.Merge(dst, src)
}
func (m *TruthParcel) XXX_Size() int {
	return xxx_messageInfo_TruthParcel.Size(m)
}
func (m *TruthParcel) XXX_DiscardUnknown() {
	xxx_messageInfo_TruthParcel.DiscardUnknown(m)
}

var xxx_messageInfo_TruthParcel proto.InternalMessageInfo

func (m *TruthParcel) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type ValueParcel struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueParcel) Reset()         { *m = ValueParcel{} }
func (m *ValueParcel) String() string { return proto.CompactTextString(m) }
func (*ValueParcel) ProtoMessage()    {}
func (*ValueParcel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{4}
}
func (m *ValueParcel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueParcel.Unmarshal(m, b)
}
func (m *ValueParcel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueParcel.Marshal(b, m, deterministic)
}
func (dst *ValueParcel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueParcel.Merge(dst, src)
}
func (m *ValueParcel) XXX_Size() int {
	return xxx_messageInfo_ValueParcel.Size(m)
}
func (m *ValueParcel) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueParcel.DiscardUnknown(m)
}

var xxx_messageInfo_ValueParcel proto.InternalMessageInfo

func (m *ValueParcel) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type IDParcel struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDParcel) Reset()         { *m = IDParcel{} }
func (m *IDParcel) String() string { return proto.CompactTextString(m) }
func (*IDParcel) ProtoMessage()    {}
func (*IDParcel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{5}
}
func (m *IDParcel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDParcel.Unmarshal(m, b)
}
func (m *IDParcel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDParcel.Marshal(b, m, deterministic)
}
func (dst *IDParcel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDParcel.Merge(dst, src)
}
func (m *IDParcel) XXX_Size() int {
	return xxx_messageInfo_IDParcel.Size(m)
}
func (m *IDParcel) XXX_DiscardUnknown() {
	xxx_messageInfo_IDParcel.DiscardUnknown(m)
}

var xxx_messageInfo_IDParcel proto.InternalMessageInfo

func (m *IDParcel) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_d06f36f5336cf43b, []int{6}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateVMOpts)(nil), "pb.CreateVMOpts")
	proto.RegisterType((*AttachDisksOpts)(nil), "pb.AttachDisksOpts")
	proto.RegisterType((*DataParcel)(nil), "pb.DataParcel")
	proto.RegisterType((*TruthParcel)(nil), "pb.TruthParcel")
	proto.RegisterType((*ValueParcel)(nil), "pb.ValueParcel")
	proto.RegisterType((*IDParcel)(nil), "pb.IDParcel")
	proto.RegisterType((*Void)(nil), "pb.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CPIDClient is the client API for CPID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CPIDClient interface {
	CreateStemcell(ctx context.Context, opts ...grpc.CallOption) (CPID_CreateStemcellClient, error)
	DeleteStemcell(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error)
	DeleteDisk(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error)
	CreateDisk(ctx context.Context, in *ValueParcel, opts ...grpc.CallOption) (*IDParcel, error)
	AttachDisk(ctx context.Context, in *AttachDisksOpts, opts ...grpc.CallOption) (*Void, error)
	HasDisk(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*TruthParcel, error)
	CreateVM(ctx context.Context, in *CreateVMOpts, opts ...grpc.CallOption) (*IDParcel, error)
	DeleteVM(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error)
	HasVM(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*TruthParcel, error)
}

type cPIDClient struct {
	cc *grpc.ClientConn
}

func NewCPIDClient(cc *grpc.ClientConn) CPIDClient {
	return &cPIDClient{cc}
}

func (c *cPIDClient) CreateStemcell(ctx context.Context, opts ...grpc.CallOption) (CPID_CreateStemcellClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CPID_serviceDesc.Streams[0], "/pb.CPID/CreateStemcell", opts...)
	if err != nil {
		return nil, err
	}
	x := &cPIDCreateStemcellClient{stream}
	return x, nil
}

type CPID_CreateStemcellClient interface {
	Send(*DataParcel) error
	CloseAndRecv() (*IDParcel, error)
	grpc.ClientStream
}

type cPIDCreateStemcellClient struct {
	grpc.ClientStream
}

func (x *cPIDCreateStemcellClient) Send(m *DataParcel) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cPIDCreateStemcellClient) CloseAndRecv() (*IDParcel, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IDParcel)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cPIDClient) DeleteStemcell(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.CPID/DeleteStemcell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) DeleteDisk(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.CPID/DeleteDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) CreateDisk(ctx context.Context, in *ValueParcel, opts ...grpc.CallOption) (*IDParcel, error) {
	out := new(IDParcel)
	err := c.cc.Invoke(ctx, "/pb.CPID/CreateDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) AttachDisk(ctx context.Context, in *AttachDisksOpts, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.CPID/AttachDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) HasDisk(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*TruthParcel, error) {
	out := new(TruthParcel)
	err := c.cc.Invoke(ctx, "/pb.CPID/HasDisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) CreateVM(ctx context.Context, in *CreateVMOpts, opts ...grpc.CallOption) (*IDParcel, error) {
	out := new(IDParcel)
	err := c.cc.Invoke(ctx, "/pb.CPID/CreateVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) DeleteVM(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.CPID/DeleteVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPIDClient) HasVM(ctx context.Context, in *IDParcel, opts ...grpc.CallOption) (*TruthParcel, error) {
	out := new(TruthParcel)
	err := c.cc.Invoke(ctx, "/pb.CPID/HasVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPIDServer is the server API for CPID service.
type CPIDServer interface {
	CreateStemcell(CPID_CreateStemcellServer) error
	DeleteStemcell(context.Context, *IDParcel) (*Void, error)
	DeleteDisk(context.Context, *IDParcel) (*Void, error)
	CreateDisk(context.Context, *ValueParcel) (*IDParcel, error)
	AttachDisk(context.Context, *AttachDisksOpts) (*Void, error)
	HasDisk(context.Context, *IDParcel) (*TruthParcel, error)
	CreateVM(context.Context, *CreateVMOpts) (*IDParcel, error)
	DeleteVM(context.Context, *IDParcel) (*Void, error)
	HasVM(context.Context, *IDParcel) (*TruthParcel, error)
}

func RegisterCPIDServer(s *grpc.Server, srv CPIDServer) {
	s.RegisterService(&_CPID_serviceDesc, srv)
}

func _CPID_CreateStemcell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CPIDServer).CreateStemcell(&cPIDCreateStemcellServer{stream})
}

type CPID_CreateStemcellServer interface {
	SendAndClose(*IDParcel) error
	Recv() (*DataParcel, error)
	grpc.ServerStream
}

type cPIDCreateStemcellServer struct {
	grpc.ServerStream
}

func (x *cPIDCreateStemcellServer) SendAndClose(m *IDParcel) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cPIDCreateStemcellServer) Recv() (*DataParcel, error) {
	m := new(DataParcel)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CPID_DeleteStemcell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).DeleteStemcell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/DeleteStemcell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).DeleteStemcell(ctx, req.(*IDParcel))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_DeleteDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).DeleteDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/DeleteDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).DeleteDisk(ctx, req.(*IDParcel))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_CreateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValueParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).CreateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/CreateDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).CreateDisk(ctx, req.(*ValueParcel))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_AttachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDisksOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).AttachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/AttachDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).AttachDisk(ctx, req.(*AttachDisksOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_HasDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).HasDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/HasDisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).HasDisk(ctx, req.(*IDParcel))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/CreateVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).CreateVM(ctx, req.(*CreateVMOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/DeleteVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).DeleteVM(ctx, req.(*IDParcel))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPID_HasVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParcel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPIDServer).HasVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CPID/HasVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPIDServer).HasVM(ctx, req.(*IDParcel))
	}
	return interceptor(ctx, in, info, handler)
}

var _CPID_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CPID",
	HandlerType: (*CPIDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteStemcell",
			Handler:    _CPID_DeleteStemcell_Handler,
		},
		{
			MethodName: "DeleteDisk",
			Handler:    _CPID_DeleteDisk_Handler,
		},
		{
			MethodName: "CreateDisk",
			Handler:    _CPID_CreateDisk_Handler,
		},
		{
			MethodName: "AttachDisk",
			Handler:    _CPID_AttachDisk_Handler,
		},
		{
			MethodName: "HasDisk",
			Handler:    _CPID_HasDisk_Handler,
		},
		{
			MethodName: "CreateVM",
			Handler:    _CPID_CreateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _CPID_DeleteVM_Handler,
		},
		{
			MethodName: "HasVM",
			Handler:    _CPID_HasVM_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStemcell",
			Handler:       _CPID_CreateStemcell_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "messages.proto",
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_d06f36f5336cf43b) }

var fileDescriptor_messages_d06f36f5336cf43b = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x6b, 0xfa, 0x30,
	0x14, 0xc5, 0xa9, 0x7f, 0xf5, 0x5f, 0xcf, 0xba, 0x3a, 0xb2, 0x31, 0xc4, 0x87, 0x21, 0x9d, 0x8c,
	0xb2, 0x81, 0x8c, 0xed, 0x79, 0x0f, 0xc3, 0x3c, 0xd8, 0x07, 0x99, 0x54, 0xe9, 0x7b, 0xd4, 0xa0,
	0xc5, 0xaa, 0xa5, 0x89, 0x7e, 0x82, 0x7d, 0xf0, 0x91, 0xd4, 0xce, 0xe8, 0xea, 0x5b, 0xee, 0xcd,
	0x2f, 0xe7, 0xdc, 0x7b, 0x73, 0xe1, 0xae, 0xb9, 0x10, 0x6c, 0xc1, 0x45, 0x2f, 0xcd, 0xb6, 0x72,
	0x4b, 0x2a, 0xe9, 0xd4, 0x9b, 0xc0, 0xe9, 0x67, 0x9c, 0x49, 0x1e, 0x0d, 0xbf, 0x52, 0x29, 0xc8,
	0x03, 0x20, 0x24, 0x5f, 0xcf, 0x78, 0x92, 0x04, 0xb4, 0x65, 0x75, 0x2c, 0xbf, 0x11, 0x1a, 0x19,
	0xd2, 0xc5, 0x35, 0x5b, 0xf0, 0x8d, 0x1c, 0x73, 0x29, 0xe3, 0xcd, 0x42, 0xb4, 0x2a, 0x1d, 0xcb,
	0x77, 0xc2, 0xd3, 0xa4, 0xf7, 0x81, 0xe6, 0xa7, 0x94, 0x6c, 0xb6, 0xa4, 0xb1, 0x58, 0x09, 0x2d,
	0x4c, 0x50, 0xdd, 0xaf, 0x7f, 0x25, 0xf5, 0x99, 0xdc, 0xa3, 0x3e, 0x8f, 0xc5, 0x2a, 0xa0, 0x5a,
	0xa5, 0x11, 0x1e, 0x22, 0xcf, 0x03, 0x28, 0x93, 0x6c, 0xc4, 0xb2, 0x19, 0x4f, 0xc8, 0x1d, 0x6a,
	0x7b, 0x96, 0xec, 0xb8, 0x7e, 0xea, 0x84, 0x79, 0xe0, 0x3d, 0xe2, 0x6a, 0x92, 0xed, 0xe4, 0xb2,
	0x0c, 0xb2, 0x0d, 0x28, 0x52, 0x87, 0x32, 0xa8, 0x56, 0x40, 0x1d, 0xd8, 0x01, 0x2d, 0x23, 0x1a,
	0x05, 0x51, 0x47, 0x35, 0xda, 0xc6, 0xf3, 0xb7, 0xef, 0x7f, 0xa8, 0xf6, 0x47, 0x01, 0x25, 0xaf,
	0x70, 0xf3, 0xa9, 0x8d, 0x0f, 0x93, 0x21, 0x6e, 0x2f, 0x9d, 0xf6, 0x8e, 0x45, 0xb7, 0x1d, 0x15,
	0x17, 0xb2, 0xbe, 0x45, 0x7c, 0xb8, 0x94, 0x27, 0xdc, 0x78, 0x71, 0x42, 0xb4, 0x6d, 0x15, 0x29,
	0x13, 0xd2, 0x05, 0x72, 0x52, 0xcd, 0xee, 0x22, 0xf5, 0x02, 0xe4, 0x15, 0x68, 0xaa, 0xa9, 0xf3,
	0xc7, 0x4e, 0x4f, 0xed, 0x15, 0x7c, 0xfc, 0x0e, 0x72, 0xab, 0xee, 0xce, 0xbe, 0xc7, 0x50, 0xf6,
	0xf1, 0x7f, 0xc0, 0x44, 0x89, 0xb9, 0x36, 0x31, 0x67, 0xfe, 0x0c, 0xbb, 0xd8, 0x1d, 0x72, 0xa3,
	0x2e, 0xcd, 0x4d, 0x3a, 0x2b, 0xc1, 0x83, 0x9d, 0x77, 0x15, 0x0d, 0x2f, 0xf6, 0xf4, 0x84, 0xda,
	0x80, 0x89, 0x3f, 0xc0, 0xb9, 0xef, 0xb4, 0xae, 0xd7, 0xf7, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x27, 0x8a, 0xc4, 0xd0, 0x02, 0x00, 0x00,
}
